spring:
  datasource:
    url: jdbc:mysql://localhost:3306/d?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password:
  redis:
    host:
    database:
    port:
  data:
    redis:
      repositories:
        enabled: false