server:
  port: 8080
spring:
  profiles:
    active: dev
  application:
    name:
  jpa:
    hibernate:
      use-new-id-generator-mappings:
kaptcha:
  config:
    props:
      kaptcha:
        border.color:
        background.clear.from:
        textproducer:
          font.color:
          font.names:
alarm:
  props:
    phone:
sms:
  url:
  user-id:
  username:
  password:
  action:
eth:
  contract:
    address: